_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml

# AcmeDemoBundle routes (to be removed)
#_acme_demo:
#    resource: "@AcmeDemoBundle/Resources/config/routing.yml"
#
#_my_routes:
#    resource: "@AcmeDemoBundle/Resources/config/myrouting.yml"
#    prefix:   /my

_planes:
    resource: "@AcmeDemoBundle/Resources/config/planerouting.yml"
    prefix:   /plane

#acme_work6:
#    resource: "@AcmeWork6Bundle/Resources/config/routing.yml"
#    prefix:   /

blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile